### ISSUE TITLE
numba issues

### ISSUE THREAD

**Issue by arita37** [AlCorreia/GeFs#1]
Thanks for your research/on GeFs.

When running your example on outlier (wine), have this msg :
Looks like a mismatch of number of params.
Would you get any idea ?

```
Traceback (most recent call last):
    rf_white.fit(X_train_white, y_train_white)
  File "GeFs/gefs/trees.py", line 513, in fit
    self.surrogate)
  File "/python3.7/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/python3.7/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.ExhaustIterConstraint object at 0x7fc636a3d390>.
**wrong tuple length for '$98call_function.6': expected 2, got 3**
During: typing of exhaust iter at GeFs/gefs/trees.py (171)
Enable logging at debug level for details.

File "../bin/GeFs/gefs/trees.py", line 171:
def build_forest(X, y, n_estimators, bootstrap, ncat, imp_measure,
    <source elided>
        for i in prange(n_estimators):
            Xtree_, ytree_ = resample_strat(X, y, n_classes)
```

**Comment by AlCorreia** [comment]
Thanks for pointing that out! There was a mismatch in the `resample_strat` return values, but it should be fixed now. If you pull the latest version, you should get no errors, but please let me know otherwise.
